apiVersion: v1
kind: Pod
metadata:
  name: drop-all-caps
  labels:
    example: basic
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      securityContext:
        capabilities:
          drop:
            - ALL
