apiVersion: v1
kind: Pod
metadata:
  name: readonly-root
  labels:
    example: basic
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
  volumes:
    - name: cache
      emptyDir: {}
    - name: run
      emptyDir: {}
