apiVersion: v1
kind: Pod
metadata:
  name: seccomp-default
  labels:
    example: basic
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: alpine
      image: alpine
      command: ["sleep", "3600"]
